
security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:4000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: localhost
      database: vimvie
      port: 27018

server:
  servlet:
    context-path: /accounts
  port: 6000

---

spring:
  profiles: prod
  spring:
    data:
      mongodb:
        host: ${MONGO_DB_HOST}
        username: ${MONGO_DB_USER}
        password: ${MONGO_DB_PASSWORD}
        port: ${MONGO_DB_PORT}

