spring:
  data:
    mongodb:
      host: localhost
      database: vimvie
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000


---

spring:
  profiles: prod
  spring:
    data:
      mongodb:
        host: ${MONGO_DB_HOST}
        username: ${MONGO_DB_USER}
        password: ${MONGO_DB_PASSWORD}
        port: ${MONGO_DB_PORT}